accounts/urls.py
from django.urls import path

from . import views

# set the app name
app_name = "accounts"

# declare the urlpatterns for the website

urlpatterns = [
    path('register/', views.register_user, name="register_user"),
    path('login/', views.login_user, name="login_user"),
    path('logout/', views.logout_user, name="logout_user"),
    path("profile/", views.profile, name="profile")

]

irrigation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("", include("main.urls"))
]

main/urls.py
from django.urls import path

from . import views

# set the app name
app_name = "main"

# declare the urlpatterns for the website

urlpatterns = [
    path('', views.home, name="home"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# create profile
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)
    started = models.BooleanField(default=False)

    def __str__(self):
        return self.phone_number

main/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
# registration form
class RegistrationForm(UserCreationForm):

    # extend from the User class
    class Meta:
        model = User

        # define fields for the form
        fields = ('username', 'email', 'password1', 'password2')

# profile form
class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile

        # fields 
        fields = ("phone_number",)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from .models import *

#  method to register account
def register_user(request):

    # check if the user is already logged in
    if request.user.is_authenticated:
        return redirect("main:home")

    # if not logged in
    else:
        if request.method == 'POST':
            form = RegistrationForm(request.POST or None)

            # check if the form is valid
            if form.is_valid():

                user = form.save(commit=False)
                user.is_active = True

                # check if the email already exists
                users = User.objects.all()

                # check for duplicate email address
                duplicate = False
                for u in users:
                    if user.email == u.email:
                        error_message = "Email Already Exists"
                        duplicate = True
                        break
                if duplicate:
                    return render(request, 'accounts/register.html', {"error_message": "Email Already Exists", "form": form})       
                else:
                    user.save()
                return redirect("accounts:login_user")
        else:
            form = RegistrationForm(request.POST or None)
        return render(request, 'accounts/register.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect("main:home")
    else:
        if request.method == 'POST':
            # now we get the data from html templates
            username = request.POST.get('username')
            password = request.POST.get('password')

            # authenticating the credentials
            user = authenticate(username=username, password=password)
            if user is not None:
                print("User is notNone") #meaning that the credentials are correct
                if user.is_active:
                    login(request, user)
                    return redirect("accounts:profile")
                else:
                    return render(request, 'accounts/login.html', {'error-message': 'Your account has been banned.'})
            else:
                return render(request, 'accounts/login.html', {'error_message': 'Invalid Username or Password'})
        return render(request, 'accounts/login.html')

# logout user
# logout
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect("accounts:login_user")
    else:
        return redirect("accounts:login_user")

# edit profile
def profile(request):
    if request.user.is_authenticated:
        # get the phone object if exists
        profile = Profile.objects.filter(user=request.user)

        # check the count
        if profile.count() >= 1:
            # prompt to edit the phone number
            return redirect("main:home")
        else:
            if request.method == "POST":
                form = ProfileForm(request.POST or None)
                if form.is_valid():
                    data = form.save(commit=False)
                    data.user = request.user
                    data.started = True
                    data.save()
                    return redirect("main:home")
            else:
                form = ProfileForm()
            return render(request, 'accounts/profile.html', {"form": form})
    else:
        return redirect("accounts:login")

main/views.py
from django.shortcuts import render, redirect
import json
import requests
# Create your views here.
def home(request):
    if request.user.is_authenticated:
        # context for the website
        # api call
        time = getTime()['time']

        # convert the time into milliseconds
        timeMs = time * 1000
        context = {
            "time": time,
            "timeMs": timeMs
        }
        return render(request, 'main/index.html', context)
    else:
        return redirect("accounts:login_user")

# here is the main logic for the program
# api call for time 
def getTime():
    requestURL = "http://ec2-3-14-152-181.us-east-2.compute.amazonaws.com/api/data/gettime"

    # get data from the api
    response = requests.get(requestURL)

    return response.json()

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}


{% block title %}
    Login
{% endblock %}


{% block content %}

{% load static %}
<br>
<div class="container">
    <div class="row">
        <div class="col s12 m8 l8">
            <div class="card">
                
                <div class="card-body">
                    <h3 class="text-center">Login To Your Account</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control"><br>
                
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control"><br>
                        {% if error_message %}
                        <i id="finish2">Please Check your Username or Password</i>
                        <br>
                    {% endif %}
                        <br>
                        <input type="submit" class="btn btn-danger" value="Login">
                        <br><br>

                        <i>Not Registered? Register a Free Account</i><a href="{% url 'accounts:register_user' %}"> Here!</a>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Before you proceed</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form |crispy }}
                <input type="submit" class="btn btn-danger" value="Update">
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col s12 m12 l8">
            <div class="card">
                
                <div class="card-body">
                    <h3 class="text-center">Register a Free Account</h3>
                    {% if error_message %}

                    <span><i style="color: red;">{{ error_message }}</i></span>

                    {% endif %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <br><br>
                        <input type="submit" class="btn btn-danger" value="Register"><br><br>
                        <i>Already a Member? Signup</i><a href="{% url 'accounts:login_user' %}"> Here!</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- custom css -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}  {% endblock %} | Irrigation</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
    <script src="{% static 'js/logic.js' %}"></script>

    {% block JavaScript %}

    {% endblock %}
    <footer>
      <div class="text-center">
        <i style="color: white;">Created By: Bibek Bhandari</i>
      </div>
    </footer>
  </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% load staticfiles %}
{% block content %}
<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Irrigation Simulation</h3>
            <div class="row">
                <div class="col-md-8">
                    <img src="{% static 'img/step1.jpg' %}" id="dynamicImage" alt="" id="image" class="img-fluid"
                        width="600">

                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                    <h3 class="text-center">Controller</h3>
                    <div class="text-center">
                        <a href="#" class="btn btn-success" onclick="loader();">Start Simulation</a>
                        <br>
                        <br><a href="#" class="btn btn-danger" id="click">Stop Simulation</a>
                    </div>
                    <div class="text-left">
                        <br><br>
                        <h4>Current Moisture Level</h4>
                        <div class="row">
                            <div class="col-md-4">Field 1: <h4 id="text">0%</h4>
                            </div>
                            <div class="col-md-4">Field 2: <h4 id="text2">0%</h4>
                            </div>
                            <div class="col-md-4">Field 3: <h4 id="text3">0%</h4>
                            </div>
                        </div>

                    </div>
                    <br>
                    <div class="text-right">
                        <a href="{% url 'accounts:logout_user' %}" class="btn btn-primary">Logout</a>
                    </div>
                </div>
            </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}